# Suppose you have a superstore which runs 24/7. Your tasks are to:

In [4]:
import numpy as np

In [7]:
Monthly = np.random.randint(low = 1, high = 100, size = (31,24))
Monthly

array([[80,  4, 53, 31, 88, 36, 76, 13, 16, 97, 70, 10, 79, 52, 70, 47,
        84, 43, 89, 16, 35, 31, 99, 82],
       [46,  1, 10, 48, 86, 36, 95, 39, 50, 30, 62, 27, 96,  8, 85, 17,
        65, 78, 68, 33, 91, 13,  7, 96],
       [25, 96, 43, 14, 35,  1, 14, 48, 12, 82, 70, 26, 52, 69, 78, 21,
         5, 69, 46, 66, 81, 64, 66, 18],
       [69, 65, 81, 31, 13, 52, 12, 86, 75, 70, 61, 60, 11, 43, 73, 83,
        59, 13, 17, 38, 37,  5, 20, 56],
       [43, 58, 41, 62, 43, 10, 72, 19, 24, 67, 58, 99, 27, 81, 80, 79,
        20, 95, 76, 27, 10, 18, 97, 96],
       [52, 42, 16, 17, 76, 31, 56, 36, 69, 41, 44,  7, 40, 15, 21, 30,
        39, 43, 58, 76, 83,  5, 44, 36],
       [61, 82, 78, 61, 79, 67, 62, 22,  6, 64, 59, 35, 45, 30, 33, 47,
        74, 62, 16, 48, 86, 18, 56, 31],
       [76, 88, 50, 84, 31, 11, 77, 58, 23, 22, 77, 84, 99, 43,  4,  2,
        96, 49, 27, 84, 44,  7,  3, 87],
       [48, 95, 88, 85, 55, 30, 53, 61, 13, 68, 62, 72, 24, 65, 34, 67,
        20, 13,  7, 10, 

2) Calculate Daily Average Sale of this dataset

In [11]:
Daily_Average = Monthly.mean(axis=1)
Daily_Average

array([54.20833333, 49.45833333, 45.875     , 47.08333333, 54.25      ,
       40.70833333, 50.91666667, 51.08333333, 47.83333333, 50.54166667,
       48.125     , 38.25      , 51.125     , 48.29166667, 50.33333333,
       54.79166667, 51.625     , 49.5       , 49.875     , 54.29166667,
       43.20833333, 45.25      , 57.08333333, 58.125     , 35.20833333,
       59.        , 52.20833333, 43.95833333, 59.66666667, 47.41666667,
       45.75      ])

3) Calculate the Average Sale of each hour, so that you have insight of the busiest hour in the month.

In [20]:
Average_Sale_per_Hour= Monthly.mean(axis = 1)
print(f"Average_Sale_per_Hour  {Average_Sale_per_Hour}")

Average_Sale_per_Hour  [54.20833333 49.45833333 45.875      47.08333333 54.25       40.70833333
 50.91666667 51.08333333 47.83333333 50.54166667 48.125      38.25
 51.125      48.29166667 50.33333333 54.79166667 51.625      49.5
 49.875      54.29166667 43.20833333 45.25       57.08333333 58.125
 35.20833333 59.         52.20833333 43.95833333 59.66666667 47.41666667
 45.75      ]


4) Calculate the minimum and Maximum Sale of each day.

In [21]:
Minimum=Monthly.min(axis = 1)
print(f"Minimum Sale  {Minimum} each day")
Maximum=Monthly.max(axis = 1)
print(f"Maximum Sale  {Maximum} Each Day")


Minimum Sale  [ 4  1  1  5 10  5  6  2  1  4  4  2  4  2  8  5  7  1  2  5  1  2  2  6
  2  6 12  8  3  2  4] each day
Maximum Sale  [99 96 96 86 99 83 86 99 95 96 99 94 99 97 96 98 98 86 99 96 91 96 98 97
 76 99 98 99 95 94 97] Each Day


5) Calculate the Minimum and Maximum Sale of each hour.

In [23]:
Minimum=Monthly.min(axis = 0)
print(f"Minimum Sale  {Minimum} each Hour")
Maximum=Monthly.max(axis = 0)
print(f"Maximum Sale  {Maximum} Each Hour")

Minimum Sale  [ 2  1  1  3  2  1  3  4  2  2  7  2 11  4  1  1  2  3  4  5  1  5  2  5] each Hour
Maximum Sale  [99 96 94 98 95 87 99 89 99 99 96 99 99 92 85 98 97 97 96 95 97 99 99 98] Each Hour


6) Calculate Daily Cumulative Sum

In [27]:
Cum_sum = Monthly.cumsum(axis = 1)
print(f'Daily Cumulative Sum   {Cum_sum}')

Daily Cumulative Sum   [[  80   84  137  168  256  292  368  381  397  494  564  574  653  705
   775  822  906  949 1038 1054 1089 1120 1219 1301]
 [  46   47   57  105  191  227  322  361  411  441  503  530  626  634
   719  736  801  879  947  980 1071 1084 1091 1187]
 [  25  121  164  178  213  214  228  276  288  370  440  466  518  587
   665  686  691  760  806  872  953 1017 1083 1101]
 [  69  134  215  246  259  311  323  409  484  554  615  675  686  729
   802  885  944  957  974 1012 1049 1054 1074 1130]
 [  43  101  142  204  247  257  329  348  372  439  497  596  623  704
   784  863  883  978 1054 1081 1091 1109 1206 1302]
 [  52   94  110  127  203  234  290  326  395  436  480  487  527  542
   563  593  632  675  733  809  892  897  941  977]
 [  61  143  221  282  361  428  490  512  518  582  641  676  721  751
   784  831  905  967  983 1031 1117 1135 1191 1222]
 [  76  164  214  298  329  340  417  475  498  520  597  681  780  823
   827  829  925  974 1001 108

7) Calculate Daily Total Sum

In [28]:
daily_total_sum = Monthly.sum(axis = 1)
print(f'Daily Total Sum  {daily_total_sum}')

Daily Total Sum  [1301 1187 1101 1130 1302  977 1222 1226 1148 1213 1155  918 1227 1159
 1208 1315 1239 1188 1197 1303 1037 1086 1370 1395  845 1416 1253 1055
 1432 1138 1098]


8) Use Boolean Indexing to search for records where sale is greater than a defined value, choose an appropriate value depending upon your dataset

In [30]:

Monthly > 90


array([[False, False, False, False, False, False, False, False, False,
         True, False, False, False, False, False, False, False, False,
        False, False, False, False,  True, False],
       [False, False, False, False, False, False,  True, False, False,
        False, False, False,  True, False, False, False, False, False,
        False, False,  True, False, False,  True],
       [False,  True, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False,  True, False, False, False, False, False,  True,
        False, False, False, False,  True,  True],
       [False, False, False, False,

8) Use Boolean Indexing to search for records where sale is greater than a defined value, choose an appropriate value depending upon your dataset

In [31]:
condition = Monthly > 90
Monthly[condition]

array([97, 99, 95, 96, 91, 96, 96, 99, 95, 97, 96, 99, 96, 95, 92, 96, 93,
       99, 96, 94, 99, 97, 96, 98, 94, 93, 98, 92, 95, 99, 95, 94, 95, 96,
       95, 91, 92, 96, 98, 95, 92, 97, 95, 92, 99, 94, 96, 99, 91, 95, 98,
       97, 93, 98, 99, 94, 97, 93, 95, 92, 94, 94, 91, 94, 97, 96])

In [33]:
Monthly_greater90 = len(Monthly[Monthly > 90])
total_hours = len(Monthly.reshape(31*24,1))
print('There are',Monthly_greater90,'hours in which you have sale more then 90rs out of',total_hours)

There are 66 hours in which you have sale more then 90rs out of 744


In [36]:
Monthly.sum(axis = 1)

array([1301, 1187, 1101, 1130, 1302,  977, 1222, 1226, 1148, 1213, 1155,
        918, 1227, 1159, 1208, 1315, 1239, 1188, 1197, 1303, 1037, 1086,
       1370, 1395,  845, 1416, 1253, 1055, 1432, 1138, 1098])

In [37]:
Monthly.sum(axis = 1) > 1000

array([ True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True])

In [39]:
days_sale1000 = len(Monthly.sum(axis = 1)[Monthly.sum(axis = 1) > 1000])
print('There are',days_sale1000,'days in which sale is greater than 1000.')

There are 28 days in which sale is greater than 1000.
